### PR TITLE
58: Release notes for hotfixes

### LINKED ISSUE #58: Create separate release notes for hotfixes
### Describe the Problem

Release notes for hotfix cannot created as for normal releases, since the relevant commits are just cherry-picked or manually created in the hotfix branch.

### Describe Your Preferred Solution

- add an option `hotfix` to specify these are release notes for an hotfix
- pass the `branch` name of the hotfix, so the current branch
- generated release notes differently by showing commits or grouping commits to an issue if possible

Example result (https://github.com/digitalfabrik/entitlementcard/tree/hotfix-2026.3.1)
```
  * #2960: Nuernberg pass bulk card creation broken                                                                                                                                                                                                                                                                    
  * Update sample data                                                                                                                                                                                                                                                                                                 
  * Do not comb form fields                                                                                                                                                                                                                                                                                          
  * Update PDF template files 
```

### Describe Possible Alternatives

<!-- A clear and concise description of any alternative solutions or features you've considered. -->

### Related Issues

<!-- Link all related issues which are e.g. CMS issues or otherwise related, blocking, duplicating issues, ... -->

### Additional Information

<!-- Add any other context (e.g. logs, screenshots, environment, related issues etc.) about the problem here. -->

### PR DESCRIPTION
**Pull request by f1sh1918**
### Short Description

Release notes for hotfixes have to created based on the commits that were done after branching from the tag.
Since we just get a couple of commit, i tried to group them if possible by issue number/prefix of the commit message

### Proposed Changes

- add option hotfix
- add option branch
- add error handling
- implement hotfix release note generation (group when possible)

### Breaking Changes

N/A

### Usage
- add `--hotfix` and the `--branch` to be able to determine the commits that were made
```
npx --no app-toolbelt v0 release create << parameters.platform >> ${NEW_VERSION_NAME} ${NEW_VERSION_CODE} --hotfix --branch ${CURRENT_BRANCH}
```

### Testing
1. Replace these lines to not trigger an actual release ⚠️ 
```
  // const release = await appOctokit.repos.createRelease({
  //   owner,
  //   repo,
  //   tag_name: newVersionName,
  //   prerelease: !productionRelease,
  //   make_latest: 'true',
  //   name: releaseName,
  //   body: releaseNotes,
  // })

  console.log(
    JSON.stringify({
      id: 'test',
      releaseNotes: formatReleaseNotesForMattermost(releaseNotes).replaceAll('\n', '\\n'),
    }),
  )
```
2. run `yarn build`
3. run this command (get the private key https://passbolt.tuerantuer.org/app/passwords/view/8108c2bd-b724-4303-ba6f-a80631e657ae)
```
 ./bin/app-toolbelt v0 release create all 2024.4.5 250 --private-key ${privateKey} --owner digitalfabrik --repo entitlementcard --hotfix --branch hotfix-2026.4.1
```
4. You should get the release notes logged in the terminal
Note: You can also use `hotfix-2026.3.1` and `hotfix-2026.4.2`

### Resolved Issues

Fixes: #58

### CODE REVIEW

File: src/github.ts [hunk 1]
```diff
@@ -136,11 +185,13 @@ export const createGithubRelease = async (
   appOctokit: Octokit,
   options: GithubReleaseOptions,
 ) => {
-  const { owner, repo, productionRelease, releaseNotes: suppliedReleaseNotes } = options
+  const { owner, repo, productionRelease, releaseNotes: suppliedReleaseNotes, hotfix, branch } = options
   const baseReleaseName = `${newVersionName} (${newVersionCode})`
   const releaseName = platform === PLATFORM_ALL ? baseReleaseName : `[${platform}] ${baseReleaseName}`
+  const previousTagName = hotfix && branch ? await findBaseTagForBranch(owner, repo, branch, appOctokit) : undefined
```
Comment (steffenkleinle) [inline src/github.ts]: 🔧 Lets keep consistent naming
```suggestion
  const previousTagName = hotfix && branch ? await findPreviousTagForBranch(owner, repo, branch, appOctokit) : undefined
```

File: src/github.ts [hunk 2]
```diff
@@ -101,22 +101,71 @@ export const commitVersion = async (
...
   try {
     const response = await appOctokit.request(getGithubApiUrlForReleaseNotes(owner, repo), {
       owner,
       repo,
       tag_name: tagName,
+      ...(previousTagName ? { previous_tag_name: previousTagName } : {}),
     })
     const generatedReleaseNotes = response.data.body
+    if (hotfix) {
+      return (await groupLinesByIssue(generatedReleaseNotes.split('\n'), owner, repo, appOctokit)).join('\n')
```
Comment (steffenkleinle) [inline src/github.ts]: 🔧 What do you think of moving the `.split()` and `.join` inside of the `groupLinesByIssue` and rename the function accordingly? i think this would make this more readable.
```suggestion
      return await groupReleaseNotesByIssue(generatedReleaseNotes, owner, repo, appOctokit)
```

File: src/github.ts [hunk 3]
```diff
@@ -101,22 +101,71 @@ export const commitVersion = async (
...
   tagName: string,
+  previousTagName?: string,
+  hotfix?: boolean,
 ): Promise<string> => {
   try {
     const response = await appOctokit.request(getGithubApiUrlForReleaseNotes(owner, repo), {
       owner,
       repo,
       tag_name: tagName,
+      ...(previousTagName ? { previous_tag_name: previousTagName } : {}),
```
Comment (steffenkleinle) [inline src/github.ts]: 🔧 `previous_tag_name` seems to accept `undefined` as value:
```suggestion
      previous_tag_name: previousTagName,
```

File: src/github.ts [hunk 4]
```diff
@@ -101,22 +101,71 @@ export const commitVersion = async (
...
 
+// For hotfixes we only get a list of commits since previous tag
+// We try to group the commits via prefix/issue nr. If thats not possible we show them ungrouped.
+const groupLinesByIssue = async (
+  lines: string[],
+  owner: string,
+  repo: string,
+  appOctokit: Octokit,
+): Promise<string[]> => {
+  const issueNumbers = [...new Set(lines.map(line => line.match(/^\* (\d+):/)?.[1]).filter(Boolean))] as string[]
```
Comment (steffenkleinle) [inline src/github.ts]: 🔧 Please extract the regex to a variable with a speaking name

Comment (steffenkleinle) [inline src/github.ts]: ❓ Why do we use the second element returned by `line.match()`?

Comment (steffenkleinle) [inline src/github.ts]: 🔧 You could add a type comparison to avoid the typecast:
```suggestion
  const issueNumbers = [...new Set(lines.map(line => line.match(/^\* (\d+):/)?.[1]).filter((it): it is string => it !== undefined))]
```

**Review by steffenkleinle — COMMENTED** [review]
Not tested, but LGTM

File: src/github.ts (hunk 4 above)
Comment (f1sh1918) [reply src/github.ts]: Because the regex /^\* (\d+):/ has a capture group (\d+). match() returns f.e. ["* 123:", "123"] — [0] is the full match including *  and :, [1] is just the captured issue number.

File: src/github.ts [hunk 5]
```diff
@@ -101,22 +101,75 @@ export const commitVersion = async (
...
+    throw new Error(`Could not find a tag matching the merge base commit ${mergeBaseSha}`)
+  }
+  return baseTag.name
+}
+
 const getGithubApiUrlForReleaseNotes = (owner: string, repo: string): string =>
   `POST /repos/${owner}/${repo}/releases/generate-notes`
 
+// For hotfixes we only get a list of commits since previous tag
+// We try to group the commits via prefix/issue nr. If thats not possible we show them ungrouped.
```
Comment (andrew8er) [inline src/github.ts]: 🔧 Here, a documentation comment (`/**`) would actually be appropriate.

File: src/github.ts [hunk 6]
```diff
@@ -101,22 +101,75 @@ export const commitVersion = async (
   return commit.data.commit.sha
 }
 
+const findBaseTagForBranch = async (
+  owner: string,
+  repo: string,
+  branch: string,
+  appOctokit: Octokit,
+): Promise<string> => {
+  const comparison = await appOctokit.repos.compareCommits({ owner, repo, base: 'main', head: branch })
```
Comment (andrew8er) [inline src/github.ts]: 🔧 Since `compareCommits()` and `listTags()` are independent of each other, we could run both queries concurrently:

```suggestion
  const [comparison, tags] = await Promise.all([
    appOctokit.repos.compareCommits({ owner, repo, base: 'main', head: branch }),
    appOctokit.repos.listTags({ owner, repo, per_page: 100 }),
  ])

File: src/github.ts [hunk 7]
```diff
@@ -101,22 +101,75 @@ export const commitVersion = async (
   return commit.data.commit.sha
 }
 
+const findBaseTagForBranch = async (
```
Comment (andrew8er) [inline src/github.ts]: 🔧 A short documentation comment that explains the meaning of "base tag" would be helpful.

File: src/github.ts [hunk 8]
```diff
@@ -101,22 +101,75 @@ export const commitVersion = async (
...
+
+  const ungrouped = lines.filter(line => !line.match(commitMessagePattern) && !line.includes('deliverino'))
+
+  const result: string[] = []
+  for (const issueNumber of issueNumbers) {
+    const { data: issue } = await appOctokit.issues.get({ owner, repo, issue_number: parseInt(issueNumber, 10) })
+    result.push(`* #${issueNumber}: ${issue.title}`)
+  }
+  result.push(...ungrouped)
+  return result.join('\n')
```
Comment (andrew8er) [inline src/github.ts]: 🔧  I can't test this, bit this should be equivalent, with the benefit that issues are queried concurrently:

```suggestion
  return issueNumbers.length === 0
    ? releaseNotes
    : [
        // Issues grouped by commit message
        ...(await Promise.all(
          issueNumbers.map(async issueNumber => {
            const { data: issue } = await appOctokit.issues.get({
              owner,
              repo,
              issue_number: parseInt(issueNumber, 10),
            })
            return `* #${issueNumber}: ${issue.title}`
          }),
        )),
        // Ungrouped commits
        ...lines.filter(line => !line.match(commitMessagePattern) && !line.includes('deliverino')),
      ].join('\n')
```

**Review by andrew8er — COMMENTED** [review]
A few suggestions.

Is there a way to test this withput specifying `--deliverino-private-key`? I tried something like this:

```sh
 node ~/Work/TaT/Digitalfabrik/app-toolbelt/dist/start.js v0 release create --web 2xxx 99 --hotfix --branch hotfix-2026.4.2
```

File: src/github.ts (hunk 4 above)
Comment (steffenkleinle) [reply src/github.ts]: Maybe splitting this line into multiple with separate steps would help a bit for readability

File: src/github.ts (hunk 7 above)
Comment (steffenkleinle) [reply src/github.ts]: And as mentioned before, I'd prefer `previousTag` here since that is our usual naming

**Review by steffenkleinle — APPROVED** [review]
Not tested

File: src/github.ts (hunk 7 above)
Comment (f1sh1918) [reply src/github.ts]: renamed and added some docs

**Review by andrew8er — APPROVED** [review]

**Comment by f1sh1918** [comment]
@steffenkleinle and @andrew8er 
I had to adjust a lot. But now everything should be properly working. I added some test instructions

**Comment by bahaaTuffaha** [comment]
> 4\. run this command (get the private key https://passbolt.tuerantuer.org/app/passwords/view/8108c2bd-b724-4303-ba6f-a80631e657ae)

This link says: `Error: this resource doesn't exist` (Logged in).

**Comment by f1sh1918** [comment]
> https://passbolt.tuerantuer.org/app/passwords/view/8108c2bd-b724-4303-ba6f-a80631e657ae

i will ask someone to add you in the particular passbolt group, i have no rights for that

**Review by bahaaTuffaha — APPROVED** [review]
hotfix-2026.4.1: (one line) ✅ 
```
{"id":"test","releaseNotes":"* #2968: Optimize `UserImportController.handleUserImport()`"}
```
hotfix-2026.3.1: (multible lines) ✅ 
```
{"id":"test","releaseNotes":"* #2960: Nuernberg pass bulk card creation broken\\n* Update sample data\\n* Do not comb form fields\\n* Update PDF template files"}
```

- Looks good but for #2968 I cant find the first commit that says`Optimize UserImportController.handleUserImport()`
- How about we add a clickable link `[#2968](https://github.com/...)` for each release note?

**Comment by f1sh1918** [comment]
> hotfix-2026.4.1: (one line) ✅
> 
> ```
> {"id":"test","releaseNotes":"* #2968: Optimize `UserImportController.handleUserImport()`"}
> ```
> 
> hotfix-2026.3.1: (multible lines) ✅
> 
> ```
> {"id":"test","releaseNotes":"* #2960: Nuernberg pass bulk card creation broken\\n* Update sample data\\n* Do not comb form fields\\n* Update PDF template files"}
> ```
> 
> * Looks good but for #2968 I cant find the first commit that says`Optimize UserImportController.handleUserImport()`
> * How about we add a clickable link `[#2968](https://github.com/...)` for each release note?

Well i don't get the first point. You can check the cherry picked commits here:
https://github.com/digitalfabrik/entitlementcard/pull/2976/commits
Then it groups all prefixed and uses the issue name of #2968.

Second point. The links works within gh automatically and that should be sufficient for this rarely used workflow
In the release notes you just write `#2968` and you can directly click on it and will be forwarded to the particular issue

**Comment by andrew8er** [comment]
I tried to test this with:
```
node ../../Digitalfabrik/app-toolbelt/dist/start.js v0 release create all 2024.4.5 250 --deliverino-private-key <redacted> --owner digitalfabrik --repo entitlementcard --hotfix --branch hotfix-2026.4.1
error: unknown option '--hotfix'
```

and commented out lines, as mentioned in the description, but I think, we need some other code to be commented out, since I also inadvertently created some tags.

I created #65 for this.

Asides from that, the code looks correct.

**Comment by f1sh1918** [comment]
> I tried to test this with:
> 
> ```
> node ../../Digitalfabrik/app-toolbelt/dist/start.js v0 release create all 2024.4.5 250 --deliverino-private-key <redacted> --owner digitalfabrik --repo entitlementcard --hotfix --branch hotfix-2026.4.1
> error: unknown option '--hotfix'
> ```
> 
> and commented out lines, as mentioned in the description, but I think, we need some other code to be commented out, since I also inadvertently created some tags.
> 
> I created #65 for this.
> 
> Asides from that, the code looks correct.

i think a dry run is good thing.
I actually tested the scenario like 20 times until the release notes were proper with the testing instructions without any issues. And baha too, so i guess the instructions should work in general and i dunno from where to problems come that you mentioned
